20170282: main.o list.o load.o add.o print.o
	gcc -o 20170282 main.o list.o load.o add.o print.o

main.o: struct.h main.c
	gcc -c main.c
list.o: struct.h list.c
	gcc -c list.c
load.o: struct.h load.c
	gcc -c load.c
add.o: struct.h add.c
	gcc -c add.c
print.o: struct.h print.c
	gcc -c print.c
